1. № вар - 3
2. № конт. - 3
3. N1 - 11
4. N2 - 9
5. N3 - 13
6. M - 8
7. Місяці - червень, липень, серпень, вересень 2023, лютий, березень,
квітень, травень 2024

### <center> Контекст 3

Компанія продає товари на два ринки – Україна та Польща. Об’єкт аналізу – щомісячні обсяги експорту.

### Завдання 1

1. Створіть таблицю для України розміром N1×22 (N1 крамниця × 12 місяців 2023 року і перші 10
місяців 2024 року). Заповніть її цілими значеннями у діапазоні від 120 до 420 включно.

In [31]:
import numpy as np
rng = np.random.default_rng(42)

ukraine = np.array(rng.integers(120, 420, size=(11, 22), endpoint=True))
ukraine

array([[146, 352, 317, 252, 250, 378, 145, 329, 180, 148, 278, 413, 341,
        349, 335, 356, 274, 158, 372, 255, 270, 231],
       [174, 398, 355, 313, 241, 367, 284, 253, 255, 188, 147, 286, 387,
        139, 378, 369, 203, 310, 169, 348, 330, 226],
       [140, 412, 254, 388, 324, 354, 348, 178, 229, 260, 269, 133, 284,
        166, 343, 325, 397, 344, 230, 411, 243, 218],
       [392, 231, 142, 261, 359, 177, 259, 159, 326, 263, 219, 188, 289,
        321, 403, 251, 168, 370, 309, 330, 149, 214],
       [351, 370, 251, 362, 373, 236, 390, 206, 192, 325, 311, 162, 370,
        180, 362, 122, 359, 356, 354, 320, 261, 332],
       [203, 354, 287, 258, 272, 291, 131, 162, 193, 154, 252, 321, 316,
        261, 377, 290, 143, 350, 292, 311, 290, 286],
       [147, 288, 359, 211, 301, 129, 224, 251, 415, 184, 203, 242, 418,
        376, 130, 190, 367, 137, 377, 204, 396, 208],
       [250, 319, 158, 287, 272, 355, 419, 319, 243, 242, 245, 365, 216,
        170, 220, 126, 151, 147, 352, 337, 329, 259],
       [335, 168, 391, 270, 402, 165, 269, 329, 269, 254, 170, 234, 191,
        210, 325, 309, 302, 228, 408, 146, 223, 155],
       [222, 409, 230, 393, 269, 330, 257, 200, 350, 411, 199, 354, 198,
        335, 357, 255, 341, 201, 143, 149, 254, 391],
       [158, 257, 331, 180, 337, 212, 363, 294, 284, 173, 259, 377, 125,
        348, 268, 336, 319, 250, 212, 308, 162, 295]])

2. Створіть таблицю для Польщі розміром N2×22 (N2 крамниця × 12 місяців 2023 року і перші 10
місяців 2024 року). Заповніть її цілими значеннями у діапазоні від 90 до 300 включно.

In [32]:
poland = np.array(rng.integers(90, 300, size=(9, 22), endpoint=True))
poland

array([[109, 227, 222, 107, 249, 177, 256,  98, 127, 194, 129, 159, 229,
        120, 232, 111, 126, 213, 257, 125, 153, 285],
       [298, 212, 184, 163, 219, 214, 152,  94, 121, 292, 178, 191, 188,
        255, 103, 107, 148, 192, 231, 193, 183, 287],
       [123, 210, 204, 189, 260, 146, 291, 159, 204, 199, 269, 182, 150,
         94, 166, 264,  92, 279, 204, 119, 153, 206],
       [156, 112, 230, 231, 115, 149, 141, 229, 244, 243, 288, 252, 157,
        112, 219, 283, 295, 138, 139,  97, 119, 207],
       [205, 168, 155, 265, 187, 260, 293, 156, 132, 291, 223, 151, 221,
        198, 281, 144, 299, 287, 128, 124, 202,  99],
       [153, 181, 294, 299, 121, 278, 109, 247, 268, 277, 137, 278, 114,
        199, 189, 156,  94, 252, 160, 229, 176, 168],
       [277, 109, 245, 247, 170, 145,  91, 287, 289, 140,  96, 115, 104,
        265, 278, 122, 247, 127, 167, 216, 241, 274],
       [ 99, 131, 149, 155, 300, 254, 157, 295, 195, 195, 181, 120, 287,
         92, 126, 138, 148, 117,  93, 232, 294, 115],
       [152, 196, 285, 236, 251, 212, 177, 132, 272, 259,  95, 240, 107,
        245, 264, 117, 181, 116, 209, 285, 107, 173]])

3. Присвойте кожному супермаркету реалістичну назву. Місяці позначте українськими назвами.

In [33]:
ukraine_stores = [f"Україна_{i+1}" for i in range(ukraine.shape[0])]
poland_stores = [f"Польща_{i+1}" for i in range(poland.shape[0])]
store_names = np.concatenate((ukraine_stores, poland_stores))

months = [
    "Січень_23", "Лютий_23", "Березень_23", "Квітень_23", "Травень_23", "Червень_23",
    "Липень_23", "Серпень_23", "Вересень_23", "Жовтень_23", "Листопад_23", "Грудень_23",
    "Січень_24", "Лютий_24", "Березень_24", "Квітень_24", "Травень_24",
    "Червень_24", "Липень_24", "Серпень_24", "Вересень_24", "Жовтень_24"
]

### Завдання 2

Створіть одну спільну таблицю такого вигляду:
* рядки – усі крамниці обох країн (усього 20 рядків);
* стовпчики – місяці для аналізу: червень, липень, серпень, вересень 2023, лютий, березень, квітень, травень 2024.
<p> Для цього візьміть зі створених у п.1 таблиць відповідні колонки і поєднайте їх по рядках у зазначеному
порядку місяців.
Далі саме ця матриця використовуватиметься для аналізу.

In [34]:
months_needed = ["Червень_23", "Липень_23", "Серпень_23", "Вересень_23",
                  "Лютий_24", "Березень_24", "Квітень_24", "Травень_24"]
columns = [months.index(m) for m in months_needed]

ukraine_sel = ukraine[:, columns]
poland_sel = poland[:, columns]

combined = np.vstack((ukraine_sel, poland_sel))
combined

array([[378, 145, 329, 180, 349, 335, 356, 274],
       [367, 284, 253, 255, 139, 378, 369, 203],
       [354, 348, 178, 229, 166, 343, 325, 397],
       [177, 259, 159, 326, 321, 403, 251, 168],
       [236, 390, 206, 192, 180, 362, 122, 359],
       [291, 131, 162, 193, 261, 377, 290, 143],
       [129, 224, 251, 415, 376, 130, 190, 367],
       [355, 419, 319, 243, 170, 220, 126, 151],
       [165, 269, 329, 269, 210, 325, 309, 302],
       [330, 257, 200, 350, 335, 357, 255, 341],
       [212, 363, 294, 284, 348, 268, 336, 319],
       [177, 256,  98, 127, 120, 232, 111, 126],
       [214, 152,  94, 121, 255, 103, 107, 148],
       [146, 291, 159, 204,  94, 166, 264,  92],
       [149, 141, 229, 244, 112, 219, 283, 295],
       [260, 293, 156, 132, 198, 281, 144, 299],
       [278, 109, 247, 268, 199, 189, 156,  94],
       [145,  91, 287, 289, 265, 278, 122, 247],
       [254, 157, 295, 195,  92, 126, 138, 148],
       [212, 177, 132, 272, 245, 264, 117, 181]])

### Завдання 3

1. Для кожного з М місяців обчисліть: суму, найбільше та найменше значення обсягів експорту
(по всіх крамницях).

In [35]:
sum_by_month = combined.sum(0)
sum_by_month

array([4829, 4756, 4377, 4788, 4435, 5356, 4371, 4654])

In [36]:
max_by_month = combined.max(axis=0)
max_by_month

array([378, 419, 329, 415, 376, 403, 369, 397])

In [37]:
min_by_month = combined.min(axis=0)
min_by_month

array([129,  91,  94, 121,  92, 103, 107,  92])

2. Для кожного обʼєкта обчисліть середній обсяг експорту за ці М місяців.

In [38]:
mean_by_month = combined.mean(axis=1)
for i, name in enumerate(store_names):
    print(f"{name}: {mean_by_month[i]}")

Україна_1: 293.25
Україна_2: 281.0
Україна_3: 292.5
Україна_4: 258.0
Україна_5: 255.875
Україна_6: 231.0
Україна_7: 260.25
Україна_8: 250.375
Україна_9: 272.25
Україна_10: 303.125
Україна_11: 303.0
Польща_1: 155.875
Польща_2: 149.25
Польща_3: 177.0
Польща_4: 209.0
Польща_5: 220.375
Польща_6: 192.5
Польща_7: 215.5
Польща_8: 175.625
Польща_9: 200.0

3. Результати подайте окремо:
* вектор із M сум;
* вектор із M найбільших значень та відповідних їм місяців і обʼєктів;
* вектор із M найменших значень та відповідних їм місяців і обʼєктів;
* вектор із N1+N2 середнього (по кожному обʼєкту).

In [42]:
sum_by_month = combined.sum(axis=0)
sum_by_month

array([4829, 4756, 4377, 4788, 4435, 5356, 4371, 4654])

In [40]:
max_values = combined.max(axis=0)
max_indices = combined.argmax(axis=0)

for m_idx, (val, s_idx) in enumerate(zip(max_values, max_indices)):
    print(f"{months_needed[m_idx]}: {store_names[s_idx]} - {val}")

Червень_23: Україна_1 - 378
Липень_23: Україна_8 - 419
Серпень_23: Україна_1 - 329
Вересень_23: Україна_7 - 415
Лютий_24: Україна_7 - 376
Березень_24: Україна_4 - 403
Квітень_24: Україна_2 - 369
Травень_24: Україна_3 - 397

In [41]:
min_values = combined.min(axis=0)
min_indices = combined.argmin(axis=0)

for m_idx, (val, s_idx) in enumerate(zip(min_values, min_indices)):
    print(f"{months_needed[m_idx]}: {store_names[s_idx]} - {val}")

Червень_23: Україна_7 - 129
Липень_23: Польща_7 - 91
Серпень_23: Польща_2 - 94
Вересень_23: Польща_2 - 121
Лютий_24: Польща_8 - 92
Березень_24: Польща_2 - 103
Квітень_24: Польща_2 - 107
Травень_24: Польща_3 - 92

### Завдання 4

### Завдання 5

### Завдання 6

### Завдання 7

### Завдання 8

### Завдання 9

### Завдання 10

### Завдання 11

### Завдання 12

### Завдання 13

### Завдання 14

### Завдання 15